/**
 * 지도 위 움직이는 그림의 프레임 목록.
 *
 * **이 파일은 스크립트가 만든 목록입니다** — 손으로 고치지 말고
 * `python scripts/make-map-sprites.py` 를 다시 돌리세요.
 *
 * 크기(w·h)는 픽셀입니다 (3배 화면 기준). 프레임 간격은 spriteClock.ts 의 TICK_MS.
 */
import type { SpriteSheet } from './spriteTypes';

export const SPRITES = {
  car: {
    lg: { w: 129, h: 96, frames: [
      require('../../../assets/sprites/car/lg-00.png'),
      require('../../../assets/sprites/car/lg-01.png'),
      require('../../../assets/sprites/car/lg-02.png'),
      require('../../../assets/sprites/car/lg-03.png'),
      require('../../../assets/sprites/car/lg-04.png'),
      require('../../../assets/sprites/car/lg-05.png'),
      require('../../../assets/sprites/car/lg-06.png'),
      require('../../../assets/sprites/car/lg-07.png'),
      require('../../../assets/sprites/car/lg-08.png'),
      require('../../../assets/sprites/car/lg-09.png'),
      require('../../../assets/sprites/car/lg-10.png'),
      require('../../../assets/sprites/car/lg-11.png'),
      require('../../../assets/sprites/car/lg-12.png'),
      require('../../../assets/sprites/car/lg-13.png'),
      require('../../../assets/sprites/car/lg-14.png'),
      require('../../../assets/sprites/car/lg-15.png'),
      require('../../../assets/sprites/car/lg-16.png'),
      require('../../../assets/sprites/car/lg-17.png'),
      require('../../../assets/sprites/car/lg-18.png'),
      require('../../../assets/sprites/car/lg-19.png'),
      require('../../../assets/sprites/car/lg-20.png'),
      require('../../../assets/sprites/car/lg-21.png'),
      require('../../../assets/sprites/car/lg-22.png'),
      require('../../../assets/sprites/car/lg-23.png'),
      require('../../../assets/sprites/car/lg-24.png'),
      require('../../../assets/sprites/car/lg-25.png'),
      require('../../../assets/sprites/car/lg-26.png'),
      require('../../../assets/sprites/car/lg-27.png'),
      require('../../../assets/sprites/car/lg-28.png'),
      require('../../../assets/sprites/car/lg-29.png'),
      require('../../../assets/sprites/car/lg-30.png'),
      require('../../../assets/sprites/car/lg-31.png'),
      require('../../../assets/sprites/car/lg-32.png'),
      require('../../../assets/sprites/car/lg-33.png'),
      require('../../../assets/sprites/car/lg-34.png'),
      require('../../../assets/sprites/car/lg-35.png'),
      require('../../../assets/sprites/car/lg-36.png'),
      require('../../../assets/sprites/car/lg-37.png'),
      require('../../../assets/sprites/car/lg-38.png'),
      require('../../../assets/sprites/car/lg-39.png'),
      require('../../../assets/sprites/car/lg-40.png'),
      require('../../../assets/sprites/car/lg-41.png'),
    ] },
    sm: { w: 81, h: 60, frames: [
      require('../../../assets/sprites/car/sm-00.png'),
      require('../../../assets/sprites/car/sm-01.png'),
      require('../../../assets/sprites/car/sm-02.png'),
      require('../../../assets/sprites/car/sm-03.png'),
      require('../../../assets/sprites/car/sm-04.png'),
      require('../../../assets/sprites/car/sm-05.png'),
      require('../../../assets/sprites/car/sm-06.png'),
      require('../../../assets/sprites/car/sm-07.png'),
      require('../../../assets/sprites/car/sm-08.png'),
      require('../../../assets/sprites/car/sm-09.png'),
      require('../../../assets/sprites/car/sm-10.png'),
      require('../../../assets/sprites/car/sm-11.png'),
      require('../../../assets/sprites/car/sm-12.png'),
      require('../../../assets/sprites/car/sm-13.png'),
      require('../../../assets/sprites/car/sm-14.png'),
      require('../../../assets/sprites/car/sm-15.png'),
      require('../../../assets/sprites/car/sm-16.png'),
      require('../../../assets/sprites/car/sm-17.png'),
      require('../../../assets/sprites/car/sm-18.png'),
      require('../../../assets/sprites/car/sm-19.png'),
      require('../../../assets/sprites/car/sm-20.png'),
      require('../../../assets/sprites/car/sm-21.png'),
      require('../../../assets/sprites/car/sm-22.png'),
      require('../../../assets/sprites/car/sm-23.png'),
      require('../../../assets/sprites/car/sm-24.png'),
      require('../../../assets/sprites/car/sm-25.png'),
      require('../../../assets/sprites/car/sm-26.png'),
      require('../../../assets/sprites/car/sm-27.png'),
      require('../../../assets/sprites/car/sm-28.png'),
      require('../../../assets/sprites/car/sm-29.png'),
      require('../../../assets/sprites/car/sm-30.png'),
      require('../../../assets/sprites/car/sm-31.png'),
      require('../../../assets/sprites/car/sm-32.png'),
      require('../../../assets/sprites/car/sm-33.png'),
      require('../../../assets/sprites/car/sm-34.png'),
      require('../../../assets/sprites/car/sm-35.png'),
      require('../../../assets/sprites/car/sm-36.png'),
      require('../../../assets/sprites/car/sm-37.png'),
      require('../../../assets/sprites/car/sm-38.png'),
      require('../../../assets/sprites/car/sm-39.png'),
      require('../../../assets/sprites/car/sm-40.png'),
      require('../../../assets/sprites/car/sm-41.png'),
    ] },
  },
  bicycle: {
    lg: { w: 117, h: 96, frames: [
      require('../../../assets/sprites/bicycle/lg-00.png'),
      require('../../../assets/sprites/bicycle/lg-01.png'),
      require('../../../assets/sprites/bicycle/lg-02.png'),
      require('../../../assets/sprites/bicycle/lg-03.png'),
      require('../../../assets/sprites/bicycle/lg-04.png'),
      require('../../../assets/sprites/bicycle/lg-05.png'),
      require('../../../assets/sprites/bicycle/lg-06.png'),
      require('../../../assets/sprites/bicycle/lg-07.png'),
      require('../../../assets/sprites/bicycle/lg-08.png'),
      require('../../../assets/sprites/bicycle/lg-09.png'),
      require('../../../assets/sprites/bicycle/lg-10.png'),
      require('../../../assets/sprites/bicycle/lg-11.png'),
      require('../../../assets/sprites/bicycle/lg-12.png'),
      require('../../../assets/sprites/bicycle/lg-13.png'),
      require('../../../assets/sprites/bicycle/lg-14.png'),
      require('../../../assets/sprites/bicycle/lg-15.png'),
      require('../../../assets/sprites/bicycle/lg-16.png'),
      require('../../../assets/sprites/bicycle/lg-17.png'),
      require('../../../assets/sprites/bicycle/lg-18.png'),
      require('../../../assets/sprites/bicycle/lg-19.png'),
      require('../../../assets/sprites/bicycle/lg-20.png'),
      require('../../../assets/sprites/bicycle/lg-21.png'),
      require('../../../assets/sprites/bicycle/lg-22.png'),
      require('../../../assets/sprites/bicycle/lg-23.png'),
      require('../../../assets/sprites/bicycle/lg-24.png'),
      require('../../../assets/sprites/bicycle/lg-25.png'),
      require('../../../assets/sprites/bicycle/lg-26.png'),
      require('../../../assets/sprites/bicycle/lg-27.png'),
      require('../../../assets/sprites/bicycle/lg-28.png'),
      require('../../../assets/sprites/bicycle/lg-29.png'),
      require('../../../assets/sprites/bicycle/lg-30.png'),
      require('../../../assets/sprites/bicycle/lg-31.png'),
      require('../../../assets/sprites/bicycle/lg-32.png'),
      require('../../../assets/sprites/bicycle/lg-33.png'),
      require('../../../assets/sprites/bicycle/lg-34.png'),
      require('../../../assets/sprites/bicycle/lg-35.png'),
      require('../../../assets/sprites/bicycle/lg-36.png'),
      require('../../../assets/sprites/bicycle/lg-37.png'),
      require('../../../assets/sprites/bicycle/lg-38.png'),
      require('../../../assets/sprites/bicycle/lg-39.png'),
      require('../../../assets/sprites/bicycle/lg-40.png'),
      require('../../../assets/sprites/bicycle/lg-41.png'),
    ] },
    sm: { w: 73, h: 60, frames: [
      require('../../../assets/sprites/bicycle/sm-00.png'),
      require('../../../assets/sprites/bicycle/sm-01.png'),
      require('../../../assets/sprites/bicycle/sm-02.png'),
      require('../../../assets/sprites/bicycle/sm-03.png'),
      require('../../../assets/sprites/bicycle/sm-04.png'),
      require('../../../assets/sprites/bicycle/sm-05.png'),
      require('../../../assets/sprites/bicycle/sm-06.png'),
      require('../../../assets/sprites/bicycle/sm-07.png'),
      require('../../../assets/sprites/bicycle/sm-08.png'),
      require('../../../assets/sprites/bicycle/sm-09.png'),
      require('../../../assets/sprites/bicycle/sm-10.png'),
      require('../../../assets/sprites/bicycle/sm-11.png'),
      require('../../../assets/sprites/bicycle/sm-12.png'),
      require('../../../assets/sprites/bicycle/sm-13.png'),
      require('../../../assets/sprites/bicycle/sm-14.png'),
      require('../../../assets/sprites/bicycle/sm-15.png'),
      require('../../../assets/sprites/bicycle/sm-16.png'),
      require('../../../assets/sprites/bicycle/sm-17.png'),
      require('../../../assets/sprites/bicycle/sm-18.png'),
      require('../../../assets/sprites/bicycle/sm-19.png'),
      require('../../../assets/sprites/bicycle/sm-20.png'),
      require('../../../assets/sprites/bicycle/sm-21.png'),
      require('../../../assets/sprites/bicycle/sm-22.png'),
      require('../../../assets/sprites/bicycle/sm-23.png'),
      require('../../../assets/sprites/bicycle/sm-24.png'),
      require('../../../assets/sprites/bicycle/sm-25.png'),
      require('../../../assets/sprites/bicycle/sm-26.png'),
      require('../../../assets/sprites/bicycle/sm-27.png'),
      require('../../../assets/sprites/bicycle/sm-28.png'),
      require('../../../assets/sprites/bicycle/sm-29.png'),
      require('../../../assets/sprites/bicycle/sm-30.png'),
      require('../../../assets/sprites/bicycle/sm-31.png'),
      require('../../../assets/sprites/bicycle/sm-32.png'),
      require('../../../assets/sprites/bicycle/sm-33.png'),
      require('../../../assets/sprites/bicycle/sm-34.png'),
      require('../../../assets/sprites/bicycle/sm-35.png'),
      require('../../../assets/sprites/bicycle/sm-36.png'),
      require('../../../assets/sprites/bicycle/sm-37.png'),
      require('../../../assets/sprites/bicycle/sm-38.png'),
      require('../../../assets/sprites/bicycle/sm-39.png'),
      require('../../../assets/sprites/bicycle/sm-40.png'),
      require('../../../assets/sprites/bicycle/sm-41.png'),
    ] },
  },
  walking: {
    lg: { w: 189, h: 96, frames: [
      require('../../../assets/sprites/walking/lg-00.png'),
      require('../../../assets/sprites/walking/lg-01.png'),
      require('../../../assets/sprites/walking/lg-02.png'),
      require('../../../assets/sprites/walking/lg-03.png'),
      require('../../../assets/sprites/walking/lg-04.png'),
      require('../../../assets/sprites/walking/lg-05.png'),
      require('../../../assets/sprites/walking/lg-06.png'),
      require('../../../assets/sprites/walking/lg-07.png'),
      require('../../../assets/sprites/walking/lg-08.png'),
      require('../../../assets/sprites/walking/lg-09.png'),
      require('../../../assets/sprites/walking/lg-10.png'),
      require('../../../assets/sprites/walking/lg-11.png'),
      require('../../../assets/sprites/walking/lg-12.png'),
      require('../../../assets/sprites/walking/lg-13.png'),
      require('../../../assets/sprites/walking/lg-14.png'),
      require('../../../assets/sprites/walking/lg-15.png'),
      require('../../../assets/sprites/walking/lg-16.png'),
      require('../../../assets/sprites/walking/lg-17.png'),
    ] },
    sm: { w: 118, h: 60, frames: [
      require('../../../assets/sprites/walking/sm-00.png'),
      require('../../../assets/sprites/walking/sm-01.png'),
      require('../../../assets/sprites/walking/sm-02.png'),
      require('../../../assets/sprites/walking/sm-03.png'),
      require('../../../assets/sprites/walking/sm-04.png'),
      require('../../../assets/sprites/walking/sm-05.png'),
      require('../../../assets/sprites/walking/sm-06.png'),
      require('../../../assets/sprites/walking/sm-07.png'),
      require('../../../assets/sprites/walking/sm-08.png'),
      require('../../../assets/sprites/walking/sm-09.png'),
      require('../../../assets/sprites/walking/sm-10.png'),
      require('../../../assets/sprites/walking/sm-11.png'),
      require('../../../assets/sprites/walking/sm-12.png'),
      require('../../../assets/sprites/walking/sm-13.png'),
      require('../../../assets/sprites/walking/sm-14.png'),
      require('../../../assets/sprites/walking/sm-15.png'),
      require('../../../assets/sprites/walking/sm-16.png'),
      require('../../../assets/sprites/walking/sm-17.png'),
    ] },
  },
  footprints: {
    lg: { w: 318, h: 318, frames: [
      require('../../../assets/sprites/footprints/lg-00.png'),
      require('../../../assets/sprites/footprints/lg-01.png'),
      require('../../../assets/sprites/footprints/lg-02.png'),
      require('../../../assets/sprites/footprints/lg-03.png'),
      require('../../../assets/sprites/footprints/lg-04.png'),
      require('../../../assets/sprites/footprints/lg-05.png'),
      require('../../../assets/sprites/footprints/lg-06.png'),
      require('../../../assets/sprites/footprints/lg-07.png'),
      require('../../../assets/sprites/footprints/lg-08.png'),
      require('../../../assets/sprites/footprints/lg-09.png'),
      require('../../../assets/sprites/footprints/lg-10.png'),
      require('../../../assets/sprites/footprints/lg-11.png'),
      require('../../../assets/sprites/footprints/lg-12.png'),
      require('../../../assets/sprites/footprints/lg-13.png'),
      require('../../../assets/sprites/footprints/lg-14.png'),
      require('../../../assets/sprites/footprints/lg-15.png'),
      require('../../../assets/sprites/footprints/lg-16.png'),
      require('../../../assets/sprites/footprints/lg-17.png'),
      require('../../../assets/sprites/footprints/lg-18.png'),
      require('../../../assets/sprites/footprints/lg-19.png'),
    ] },
  },
} satisfies Record<string, Record<string, SpriteSheet>>;
